# Generated by Django 2.1.8 on 2019-07-11 16:32

import assets.models.asset
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='访问地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '应用系统',
                'verbose_name_plural': '应用系统',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='主机名')),
                ('ip', models.CharField(db_index=True, max_length=128, verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, null=True, verbose_name='端口')),
                ('platform', models.CharField(choices=[('Linux', 'Linux'), ('Unix', 'Unix'), ('Windows', 'Windows'), ('Other', 'Other')], default='Linux', max_length=128, verbose_name='系统平台')),
                ('assettype', models.IntegerField(choices=[(1, '实体机'), (2, '虚拟机'), (3, '存储'), (4, '交换机')], default=1, verbose_name='资产类型')),
                ('is_formal', models.BooleanField(choices=[(1, '生产'), (2, '测试')], default=False, verbose_name='是否正式环境')),
                ('model', models.CharField(blank=True, max_length=54, null=True, verbose_name='资产型号')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU model')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU count')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU cores')),
                ('cpu_vcpus', models.IntegerField(blank=True, null=True, verbose_name='CPU vcpus')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='Memory')),
                ('disk_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disk_total')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('appinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AppInfo', verbose_name='应用系统')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=128)),
                ('child_mark', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '节点',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='操作系统名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作系统',
                'verbose_name_plural': '操作系统',
            },
        ),
        migrations.CreateModel(
            name='UserProfileManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_Admin')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AppInfo', verbose_name='应用')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='资产')),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='nodes',
            field=models.ForeignKey(default=assets.models.asset.default_node, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.Node'),
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.OperatingSystem', verbose_name='操作系统'),
        ),
    ]
