# Generated by Django 2.1.8 on 2019-07-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='主机名'),
        ),
    ]
