# Generated by Django 2.1.8 on 2019-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190712_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_formal',
            field=models.BooleanField(default=True, verbose_name='是否正式环境'),
        ),
    ]
