# Generated by Django 2.1.8 on 2019-07-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20190719_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetuser',
            unique_together={('username', 'password')},
        ),
    ]
