# Generated by Django 2.1.8 on 2019-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文件名')),
                ('file', models.FileField(upload_to='uploads/%Y/%m', verbose_name='文件路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('download_nums', models.IntegerField(default=0, verbose_name='下载量')),
            ],
        ),
    ]
